// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJAxBFQ0i55w6CTWL0SeYLy6LvYc-Ji5Y',
    appId: '1:131151356388:web:603803ff4fcc517e24e7f1',
    messagingSenderId: '131151356388',
    projectId: 'london-crime-27067',
    authDomain: 'london-crime-27067.firebaseapp.com',
    storageBucket: 'london-crime-27067.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGYV7DqbpynOj_vi8uvPWZEDb_P8nXpNU',
    appId: '1:131151356388:android:5cdc1f593076ae8724e7f1',
    messagingSenderId: '131151356388',
    projectId: 'london-crime-27067',
    storageBucket: 'london-crime-27067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk-GAYHzW3360w4OaOvjeIPdVc6PWVEMs',
    appId: '1:131151356388:ios:550d8fd916b1232424e7f1',
    messagingSenderId: '131151356388',
    projectId: 'london-crime-27067',
    storageBucket: 'london-crime-27067.firebasestorage.app',
    iosBundleId: 'com.gs.londonCrime',
  );
}
